-- Seed ~50 forum threads
-- I will need to get the user IDs and category IDs from the database to create these threads.
-- For now, I will use placeholders and then replace them with the actual IDs.

-- To get user IDs: SELECT id, username FROM profiles;
-- To get category IDs: SELECT id, name FROM forum_categories;

-- Placeholder IDs
-- Users: SaltyDog, MarinaMama, EngineGuru, SailorSue, FishinFrank, etc.
-- Categories: General Discussion, Technical & Maintenance, Buying & Selling Advice, etc.

INSERT INTO forum_threads (id, category_id, author_id, title, content, thread_type, created_at) VALUES
-- January
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Technical & Maintenance'), (SELECT id FROM profiles WHERE username = 'EngineGuru'), 'Winterizing a Yamaha 250 - Best Practices?', 'Hey all, first winter with my new boat. What are the must-do steps for winterizing a Yamaha 250? I''m in North Florida, so we get a few light freezes. Don''t want to mess this up. Thanks!', 'question', '2025-01-10 10:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'General Discussion'), (SELECT id FROM profiles WHERE username = 'SaltyDog'), 'Best sandbar spot in the Keys?', 'Been going to Marvin Key for years, but looking for a new spot to anchor up for the day. Any hidden gems I should know about? My draft is 4 feet.', 'discussion', '2025-01-15 14:30:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Buying & Selling Advice'), (SELECT id FROM profiles WHERE username = 'BoatBrokerBen'), 'Thinking of selling? Now is the time!', 'Just a heads up to everyone, the market is hot right now for used center consoles in the 20-25 foot range. If you''re on the fence about selling, you might be surprised what you can get. Happy to answer any questions.', 'announcement', '2025-01-20 09:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Sailing'), (SELECT id FROM profiles WHERE username = 'SailorSue'), 'First solo sail - a comedy of errors', 'lol so I tried my first solo sail yesterday on my Catalina 22. Let''s just say it involved a dropped winch handle, a tangled mainsheet, and a very patient dolphin who seemed to be laughing at me. Any tips for a newbie solo sailor?', 'discussion', '2025-01-25 18:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Fishing'), (SELECT id FROM profiles WHERE username = 'FishinFrank'), 'Where are the snook biting?', 'I''m in JAX and the bite has been slow for me. Anyone having any luck further south? Thinking of trailering down to the Indian River.', 'question', '2025-01-28 12:00:00'),

-- February
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Technical & Maintenance'), (SELECT id FROM profiles WHERE username = 'DIYDiver'), 'Fiberglass repair - what''s your go-to epoxy?', 'Got a few dings on my old Mako that I need to patch up. What''s everyone using for small fiberglass repairs? West System? MAS? Something else?', 'question', '2025-02-05 11:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Destinations & Cruising'), (SELECT id FROM profiles WHERE username = 'IslandHopper'), 'Planning a Bahamas trip in May - tips?', 'Hey everyone, planning a trip to the Abacos in May. First time crossing. Any advice on the best route from West Palm? What are the must-see spots?', 'discussion', '2025-02-10 16:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'General Discussion'), (SELECT id FROM profiles WHERE username = 'PontoonParty'), 'Best speakers for a pontoon boat?', 'Looking to upgrade the sound system on our pontoon. What are the best marine speakers for a party boat? Need something loud and clear.', 'question', '2025-02-18 20:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Safety & Regulations'), (SELECT id FROM profiles WHERE username = 'TheSurveyor'), 'Don''t forget to check your fire extinguishers!', 'Friendly reminder to everyone to check the dates on your fire extinguishers. It''s one of the first things I look for during a survey, and it''s an easy thing to overlook.', 'announcement', '2025-02-22 08:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Power Boats'), (SELECT id FROM profiles WHERE username = 'YachtLife'), 'Fuel consumption on a 60ft Azimut', 'Thinking of upgrading to the new Azimut 60 Fly. Anyone have real-world fuel consumption numbers? The brochure seems a little... optimistic.', 'question', '2025-02-28 13:00:00'),

-- March
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Technical & Maintenance'), (SELECT id FROM profiles WHERE username = 'PropellerHead'), 'Prop pitch question', 'I have a 22ft pathfinder with a 200hp yamaha. Currently running a 19p prop, but I feel like I''m not getting the top end I should. WOT is 5500rpm. Should I go up to a 21p?', 'question', '2025-03-05 19:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'General Discussion'), (SELECT id FROM profiles WHERE username = 'NewbieNavigator'), 'Docking in a crosswind - HELP!', 'Had my first experience docking with a strong crosswind yesterday. It was... not pretty. Any tips or tricks for a new boater? I have a single engine bowrider.', 'question', '2025-03-12 17:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Fishing'), (SELECT id FROM profiles WHERE username = 'TackleBoxTom'), 'Best bait for tarpon?', 'It''s almost tarpon season! What''s everyone''s go-to bait? Live mullet? Crabs? Something else?', 'question', '2025-03-18 15:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Sailing'), (SELECT id FROM profiles WHERE username = 'SailAway'), 'What''s a realistic budget for a full-time cruiser?', 'My partner and I are saving up to go full-time cruising in a few years. For those of you who are already out there, what''s a realistic monthly budget for a couple on a 40-foot monohull?', 'question', '2025-03-25 11:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Buying & Selling Advice'), (SELECT id FROM profiles WHERE username = 'TheSurveyor'), 'Red flags to look for when buying a used boat', 'Here are my top 5 red flags when I''m surveying a used boat: 1. Fresh bottom paint with no records. 2. Mismatched gelcoat repairs. 3. Water in the bilge. 4. Messy wiring. 5. A seller who won''t let you talk to their mechanic. What are yours?', 'discussion', '2025-03-30 10:00:00'),

-- April
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Technical & Maintenance'), (SELECT id FROM profiles WHERE username = 'TheWrench'), 'Changing a water pump impeller - easier than you think', 'Just wanted to share a quick tutorial on how to change the water pump impeller on a Yamaha outboard. It''s a job anyone can do with a few basic tools and it will save you a few hundred bucks. Here''s how...', 'discussion', '2025-04-04 14:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Destinations & Cruising'), (SELECT id FROM profiles WHERE username = 'AnchorDown'), 'Dry Tortugas trip report', 'Just got back from a week at the Dry Tortugas. Absolutely incredible. The snorkeling was amazing and the fort is a must-see. Here are a few pics and some tips for anyone planning a trip.', 'discussion', '2025-04-11 12:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'General Discussion'), (SELECT id FROM profiles WHERE username = 'MarinaMama'), 'How do you deal with difficult slip neighbors?', 'We''ve all had them. The guy who plays loud music at all hours, the one who doesn''t know how to tie a proper spring line... what are your best strategies for dealing with difficult slip neighbors?', 'discussion', '2025-04-18 16:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Power Boats'), (SELECT id FROM profiles WHERE username = 'go_fast_guy'), 'What''s the fastest you''ve ever been on the water?', 'Just hit 85mph in my Fountain. What''s the fastest you guys have been?', 'discussion', '2025-04-25 21:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Safety & Regulations'), (SELECT id FROM profiles WHERE username = 'SaltyDog'), 'A reminder about the rules of the road', 'Had a close call with a jet ski yesterday. A good reminder for everyone to brush up on the rules of the road. Remember, the vessel with the right of way is the one that is less maneuverable. That''s usually not the jet ski.', 'announcement', '2025-04-29 09:00:00'),

-- May
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Technical & Maintenance'), (SELECT id FROM profiles WHERE username = 'GelcoatGenius'), 'The art of wet sanding', 'A lot of people are scared of wet sanding, but it''s the key to getting a mirror finish on your gelcoat. Here''s my process...', 'discussion', '2025-05-03 13:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Fishing'), (SELECT id FROM profiles WHERE username = 'ReelDeal'), 'Book your summer fishing charters now!', 'The summer season is filling up fast. If you''re looking to book a charter in the Destin area, now is the time to do it. The bite is hot!', 'announcement', '2025-05-08 10:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'General Discussion'), (SELECT id FROM profiles WHERE username = 'KnottyBuoy'), 'What''s the most useless piece of boat gear you''ve ever bought?', 'I''ll start. A solar-powered anchor light that died after two weeks.', 'discussion', '2025-05-15 19:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Buying & Selling Advice'), (SELECT id FROM profiles WHERE username = 'NewbieNavigator'), 'Is a survey really necessary for a new boat?', 'We''re looking at a brand new 2025 model. The dealer says a survey isn''t necessary. What do you guys think?', 'question', '2025-05-22 14:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Sailing'), (SELECT id FROM profiles WHERE username = 'RiggingMaster'), 'When should you replace your standing rigging?', 'What''s the general consensus on when to replace standing rigging? Every 10 years? 15? Or just when you see signs of wear?', 'question', '2025-05-28 11:00:00'),

-- June
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Technical & Maintenance'), (SELECT id FROM profiles WHERE username = 'BottomPaintPro'), 'Best bottom paint for Florida waters?', 'I''m getting ready to haul out and do my bottom paint. What''s everyone having the best luck with in Florida? I''m in the water year-round.', 'question', '2025-06-02 15:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Destinations & Cruising'), (SELECT id FROM profiles WHERE username = 'TrawlerLife'), 'The Great Loop - anyone done it?', 'My wife and I are planning to do the Great Loop in a few years. For those who have done it, what was your favorite part? Any advice for a couple of newbies?', 'discussion', '2025-06-09 12:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'General Discussion'), (SELECT id FROM profiles WHERE username = 'TheCaptain'), 'What''s your go-to boat drink?', 'It''s getting hot out there. What''s everyone''s favorite boat drink? I''m a classic rum and coke guy myself.', 'discussion', '2025-06-16 17:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Power Boats'), (SELECT id FROM profiles WHERE username = 'OutboardAndy'), 'Two-stroke vs. four-stroke - let''s settle it', 'I know this has been debated a million times, but let''s hear it. What''s better and why? I''m a two-stroke guy all the way.', 'discussion', '2025-06-23 19:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Fishing'), (SELECT id FROM profiles WHERE username = 'casting_queen'), 'Ladies, what''s your favorite fishing gear?', 'Looking for recommendations on fishing gear designed for women. What are your favorite rods, reels, and apparel?', 'question', '2025-06-28 10:00:00'),

-- July
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'Events & Meetups'), (SELECT id FROM profiles WHERE username = 'SaltyDog'), '4th of July fireworks from the water?', 'Anyone know the best spot to watch the 4th of July fireworks from the water in the Keys? Looking for a good spot to anchor up.', 'question', '2025-07-01 11:00:00'),
(gen_random_uuid(), (SELECT id FROM forum_categories WHERE name = 'General Discussion'), (SELECT id FROM profiles WHERE username = 'ReefRunner'), 'It''s hot. So hot.', 'That is all.', 'discussion', '2025-07-02 15:00:00');
